server:
  port: 8081
  servlet:
    session:
      timeout: 15s
      cookie:
        http-only: true
        secure: false
spring:
  application:
    name: springboot-security
  datasource:
    username: root
    password: 2648
    url: jdbc:mysql://192.168.1.26:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  security:
    loginType: JSON
    user:
      name: admin
      password: admin
mybatis:
  mapper-locations: classpath:mapper/*.xml