server:
  port: 8081
  servlet:
    context-path: /springboot-security
spring:
  datasource:
    username: root
    password: 2648
    url: jdbc:mysql://192.168.107.6:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  application:
    name: springboot-security
  security:
    loginType: JSON
    user:
      name: admin
      password: admin